services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8888:443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY= # echo -n 'base64:'; openssl rand -base64 32
      - APP_URL=http://localhost
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE='0 * * * *'
      - PRUNE_RESULTS_OLDER_THAN="365"
      - APP_TIMEZONE='Australia/Melbourne'
      - DISPLAY_TIMEZONE='Australia/Melbourne'
      - PUBLIC_DASHBOARD="true"
    volumes:
      - ./data:/config
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
